# Generated by Django 4.0.1 on 2022-01-19 12:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=django.contrib.auth.models.User, max_length=50)),
                ('video', models.FileField(upload_to='')),
                ('data', models.DateField(blank=True)),
                ('legenda', models.TextField(max_length=2200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=django.contrib.auth.models.User, max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
                ('data', models.DateField(blank=True)),
                ('legenda', models.TextField(max_length=2200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('programacao', models.TextField(max_length=500)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicos.foto')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicos.video')),
            ],
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('motivos', models.CharField(max_length=2200, verbose_name='Quais os motivos que te levaram a abrir um perfil profissional?')),
                ('perfil', models.CharField(max_length=2200, verbose_name='Como você vê o seu perfil em 5 anos? E em 10?')),
                ('segmento', models.CharField(max_length=2200, verbose_name='Seu perfil pode ser outra coisa no futuro ou atuar em outro segmento? Se sim, o que seria?')),
                ('projeto_identidade', models.CharField(max_length=2200, verbose_name='O que te fez me procurar para criar um projeto de Identidade Visual. Por que isso é importante pra você e para seu instagram?')),
                ('conta_profissional', models.CharField(max_length=2200, verbose_name='Por que você acredita que as pessoas precisam da sua conta profissional?')),
                ('rede_social', models.CharField(max_length=2200, verbose_name='Defina resumidamente do que se trata sua rede social')),
                ('rede_profissional', models.CharField(max_length=2200, verbose_name='Há quanto tempo sua rede social profissional existe?')),
                ('rede_especial', models.CharField(max_length=2200, verbose_name='O que faz sua rede social ser especial?')),
                ('slogan', models.CharField(max_length=2200, verbose_name='Sua rede social tem algum slogan?')),
                ('concorrentes', models.CharField(max_length=2200, verbose_name='Sua rede social tem concorrentes? Quem são? Fale um pouco sobre eles se achar necessário. Coloque nomes e links se puder')),
                ('concorrentes_oferecem', models.CharField(max_length=2200, verbose_name='Seus concorrentes oferecem algo que você não oferece?')),
                ('missoes', models.CharField(max_length=2200, verbose_name='Quais missões, visões e valores da sua conta social profissional?')),
                ('faixa_etaria_social', models.CharField(max_length=500, verbose_name='Qual a Faixa Etária e Classe Social?')),
                ('genero', models.CharField(choices=[('Totalmente masculino', 'Totalmente masculino'), ('Masculino predominante, pouco feminino', 'Masculino predominante, pouco feminino'), ('Ambos os gêneros', 'Ambos os gêneros'), ('Feminino predominante, pouco masculino', 'Feminino predominante, pouco masculino'), ('Totalmente feminino', 'Totalmente feminino')], max_length=38, verbose_name='Gênero')),
                ('quem', models.CharField(max_length=500, verbose_name='Quem são eles? Descreva com suas palavras.')),
                ('descricao_clientes', models.CharField(max_length=500, verbose_name='Como você gostaria que os clientes descrevessem seu instagram?')),
                ('encontrar_clientes', models.CharField(max_length=500, verbose_name='De que forma você espera que seu cliente encontre seu instagram?')),
                ('logotipo_clientes', models.CharField(max_length=500, verbose_name='Quais os locais você acredita que seu cliente mais verá o logotipo do seu instagram. Acrescente por ordem de importância.')),
                ('personalidade', multiselectfield.db.fields.MultiSelectField(choices=[('Séria', 'Séria'), ('Alegre', 'Alegre'), ('Conservadora', 'Conservadora'), ('Nerd', 'Nerd'), ('Discreta', 'Discreta'), ('Sensível', 'Sensível'), ('Aventureira', 'Aventureira'), ('Tradicional', 'Tradicional'), ('Líder', 'Líder'), ('Sábia', 'Sábia'), ('Exclusiva', 'Exclusiva'), ('Científica', 'Científica'), ('Técnica', 'Técnica'), ('Grande', 'Grande'), ('Complexa', 'Complexa'), ('Rústica', 'Rústica'), ('Futurista', 'Futurista'), ('Racional', 'Racional'), ('Mente Aberta', 'Mente Aberta'), ('Divertida', 'Divertida'), ('Emocional', 'Emocional'), ('Intuitiva', 'Intuitiva'), ('Diferente', 'Diferente'), ('Curiosa', 'Curiosa'), ('Disciplinada', 'Disciplinada'), ('Respeitadora', 'Respeitadora'), ('Arrojada', 'Arrojada'), ('Séria', 'Séria'), ('Acessível', 'Acessível'), ('Reservada', 'Reservada'), ('Esperta', 'Esperta'), ('Atual', 'Atual'), ('Inocente', 'Inocente'), ('Acadêmica', 'Acadêmica'), ('Sutil', 'Sutil'), ('Básica', 'Básica'), ('Rigorosa', 'Rigorosa'), ('Idealista', 'Idealista'), ('Pequena', 'Pequena'), ('Radical', 'Radical'), ('Grosseira', 'Grosseira'), ('Previsível', 'Previsível'), ('Pessimista', 'Pessimista'), ('Refinada', 'Refinada'), ('Da Massa', 'Da Massa'), ('Industrial', 'Industrial'), ('Comum', 'Comum'), ('Extrovertida', 'Extrovertida'), ('Brincalhona', 'Brincalhona'), ('Moderna', 'Moderna'), ('Elegante', 'Elegante'), ('Delicada', 'Delicada'), ('Madura', 'Madura'), ('Rebelde', 'Rebelde'), ('Calma', 'Calma'), ('Energética', 'Energética'), ('Criativa', 'Criativa'), ('Romântica', 'Romântica'), ('Ousada', 'Ousada'), ('Arrogante', 'Arrogante'), ('Sóbria', 'Sóbria'), ('Formal', 'Formal'), ('Antiga', 'Antiga'), ('Determinada', 'Determinada'), ('Relaxada', 'Relaxada'), ('Irreverente', 'Irreverente'), ('Tranquila', 'Tranquila'), ('Confiável', 'Confiável'), ('Persistente', 'Persistente'), ('Profissional', 'Profissional'), ('Analítica', 'Analítica'), ('Artística', 'Artística'), ('Modesta', 'Modesta'), ('Deslumbrante', 'Deslumbrante'), ('Padronizada', 'Padronizada'), ('Livre', 'Livre'), ('Estável', 'Estável'), ('Moderna', 'Moderna'), ('Casual', 'Casual'), ('Sonhadora', 'Sonhadora'), ('Agressiva', 'Agressiva'), ('Convencional', 'Convencional'), ('Simples', 'Simples'), ('Atrevida', 'Atrevida'), ('Cotidiana', 'Cotidiana'), ('Multifacetada', 'Multifacetada'), ('Promissora', 'Promissora'), ('Enigmática', 'Enigmática'), ('Nostálgica', 'Nostálgica'), ('Outro', 'Outra')], max_length=1500, verbose_name='Se seu instagram fosse uma pessoa como ela seria? Escolha quantas opções julgar necessário:')),
                ('palavras', models.CharField(max_length=64, verbose_name='Dessas palavras que você escolheu, cite 3 que você considera mais forte.')),
                ('pessoa', models.CharField(max_length=500, verbose_name='Se seu instagram fosse uma pessoa, como ele seria?')),
                ('caracteristicas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Se necessário, adicione mais algumas características.')),
                ('cor', models.CharField(max_length=100, verbose_name='Há alguma cor que você queira na sua marca?')),
                ('nao_cor', models.CharField(max_length=100, verbose_name='Há alguma cor que você NÃO queira na sua marca?')),
                ('nao_elemento', models.CharField(max_length=100, verbose_name='Há algum elemento que você NÃO queira na sua marca?')),
                ('aspectos', multiselectfield.db.fields.MultiSelectField(choices=[('Séria', 'Séria'), ('Conservadora', 'Conservadora'), ('Aconchegante', 'Aconchegante'), ('Moderna', 'Moderna'), ('Sofisticada', 'Sofisticada'), ('Vibrante', 'Vibrante'), ('Retrô', 'Retrô'), ('Pesada', 'Pesada'), ('Rústica', 'Rústica'), ('Extravagante', 'Extravagante'), ('Popular', 'Popular'), ('Formal', 'Formal'), ('Humana', 'Humana'), ('Irreverente', 'Irreverente'), ('Extrovertida', 'Extrovertida'), ('Alegre', 'Alegre'), ('Delicada', 'Delicada'), ('Orgânica', 'Orgânica'), ('Elegante', 'Elegante'), ('Tradicional', 'Tradicional'), ('Digital', 'Digital'), ('Leve', 'Leve'), ('Discreta', 'Discreta'), ('Nobre', 'Nobre'), ('Romântica', 'Romântica'), ('Ousada', 'Ousada'), ('Rebelde', 'Rebelde'), ('Outra', 'Outra')], max_length=500, verbose_name='Pensando apenas em aspectos visuais, selecione alguns atributos que têm alguma relação com a sua marca.')),
                ('consideracoes', models.CharField(max_length=500, verbose_name='Fique a vontade para dizer mais sobre a sua empresa ou dar considerações finais.')),
                ('referencias', models.CharField(help_text='Referências de imagens ou de marcas que você gosta é muito válido, embora nós iremos montar nossa própria identidade visual.', max_length=500, verbose_name='Tem alguma referência?')),
                ('cliente', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
