# Generated by Django 4.0.1 on 2022-01-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_rename_post_fotos_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='FotosPost',
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(help_text='Essa imagem deve ser igual a Fotos #1', upload_to=''),
        ),
    ]
