# Generated by Django 4.0.1 on 2022-01-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_rename_fotos_fotospost_alter_foto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='outra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outra'),
        ),
    ]
