# Generated by Django 4.0.1 on 2022-01-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0008_briefing_outra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing',
            name='consideracoes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Fique a vontade para dizer mais sobre a sua empresa ou dar considerações finais.'),
        ),
    ]
